/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsylvan_JSylvan */

#ifndef _Included_jsylvan_JSylvan
#define _Included_jsylvan_JSylvan
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jsylvan_JSylvan
 * Method:    quit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jsylvan_JSylvan_quit
  (JNIEnv *, jclass);

/*
 * Class:     jsylvan_JSylvan
 * Method:    setGranularity
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jsylvan_JSylvan_setGranularity
  (JNIEnv *, jclass, jint);

/*
 * Class:     jsylvan_JSylvan
 * Method:    makeVar
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_makeVar
  (JNIEnv *, jclass, jint);

/*
 * Class:     jsylvan_JSylvan
 * Method:    makeNot
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_makeNot
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    makeAnd
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_makeAnd
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    makeOr
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_makeOr
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    makeImplies
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_makeImplies
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    makeIte
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_makeIte
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    makeEquals
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_makeEquals
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    makeNotEquals
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_makeNotEquals
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    makeExists
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_makeExists
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    makeForall
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_makeForall
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    makeProject
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_makeProject
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    makeAndExists
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_makeAndExists
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    makeAndProject
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_makeAndProject
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    makeNext
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_makeNext
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    makePrev
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_makePrev
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    makeClosure
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_makeClosure
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    makeUnionPar
 * Signature: ([J)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_makeUnionPar
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     jsylvan_JSylvan
 * Method:    makeConstrain
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_makeConstrain
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    makeRestrict
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_makeRestrict
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    ref
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_ref
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    deref
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jsylvan_JSylvan_deref
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    countRefs
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_countRefs
  (JNIEnv *, jclass);

/*
 * Class:     jsylvan_JSylvan
 * Method:    getVar
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jsylvan_JSylvan_getVar
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    getIf
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_getIf
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    getThen
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_getThen
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    getElse
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_getElse
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    print
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jsylvan_JSylvan_print
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    fprint
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_jsylvan_JSylvan_fprint
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    printDot
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jsylvan_JSylvan_printDot
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    fprintDot
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_jsylvan_JSylvan_fprintDot
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    disableGC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jsylvan_JSylvan_disableGC
  (JNIEnv *, jclass);

/*
 * Class:     jsylvan_JSylvan
 * Method:    enableGC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jsylvan_JSylvan_enableGC
  (JNIEnv *, jclass);

/*
 * Class:     jsylvan_JSylvan
 * Method:    gc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jsylvan_JSylvan_gc
  (JNIEnv *, jclass);

/*
 * Class:     jsylvan_JSylvan
 * Method:    getTableUsed
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_getTableUsed
  (JNIEnv *, jclass);

/*
 * Class:     jsylvan_JSylvan
 * Method:    getTableSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_getTableSize
  (JNIEnv *, jclass);

/*
 * Class:     jsylvan_JSylvan
 * Method:    getNodesCreated
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_getNodesCreated
  (JNIEnv *, jclass);

/*
 * Class:     jsylvan_JSylvan
 * Method:    satcount
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_jsylvan_JSylvan_satcount
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    nodecount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_nodecount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    makeSupport
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_makeSupport
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    mapEmpty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_mapEmpty
  (JNIEnv *, jclass);

/*
 * Class:     jsylvan_JSylvan
 * Method:    mapIsEmpty
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jsylvan_JSylvan_mapIsEmpty
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    mapKey
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jsylvan_JSylvan_mapKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    mapValue
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_mapValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    mapNext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_mapNext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    mapContains
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_jsylvan_JSylvan_mapContains
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jsylvan_JSylvan
 * Method:    mapCount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_mapCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    mapAdd
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_mapAdd
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    mapUpdate
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_mapUpdate
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    mapRemove
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_mapRemove
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jsylvan_JSylvan
 * Method:    mapRemoveAll
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_mapRemoveAll
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    compose
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jsylvan_JSylvan_compose
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    setLimits
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_jsylvan_JSylvan_setLimits
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jsylvan_JSylvan
 * Method:    setSizes
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_jsylvan_JSylvan_setSizes
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    initLace
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_jsylvan_JSylvan_initLace
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jsylvan_JSylvan
 * Method:    initPackage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jsylvan_JSylvan_initPackage
  (JNIEnv *, jclass);

/*
 * Class:     jsylvan_JSylvan
 * Method:    initMtbdd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jsylvan_JSylvan_initMtbdd
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
