/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsylvan_MCFile */

#ifndef _Included_jsylvan_MCFile
#define _Included_jsylvan_MCFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jsylvan_MCFile
 * Method:    fromFile
 * Signature: (Ljava/lang/String;)Ljsylvan/MCFile;
 */
JNIEXPORT jobject JNICALL Java_jsylvan_MCFile_fromFile
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
